/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kovacevic.view;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import kovacevic.controller.Obrada;
import kovacevic.model.Materijal;
import kovacevic.pomocno.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Marko Kovačević
 */
public class FormaMaterijal extends Forma<Materijal> {

    private List<Materijal> rezultati;

    /**
     * Creates new form FormaMaterijal
     */
    public FormaMaterijal() {
        initComponents();
        setTitle("Materijal");
        obrada = new Obrada();

        ucitaj();
    }

    @Override
    protected void ucitaj() {
        Session session=HibernateUtil.getSession();
        session.clear();
        rezultati = HibernateUtil.getSession().createQuery("from Materijal a where a.obrisan=false").list();
        ucitavanje();

    }

    private void ucitavanje() {
        DefaultListModel<Materijal> m = new DefaultListModel<>();
        lista.setModel(m);
        rezultati.forEach((s) -> {
            m.addElement(s);
        });

    }

    @Override
    protected void spremi() {
        entitet.setGrupa_materijal(txtGrupaMaterijal.getText());
        entitet.setProizvodac(txtProizvodac.getText());
        entitet.setOznaka(txtOznaka.getText());
        entitet.setKolicina_ambalaza(new BigDecimal(txtKolicinaAmbalaza.getText()));
        entitet.setJedinica_mjere_ambalaza(txtJedinicaMjereAmbalaza.getText());
        entitet.setCijena_ambalaza(new BigDecimal(txtCijenaAmbalaza.getText()));
        entitet.setOpis(tarOpis.getText());
        super.spremi();
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        lblGrupaMaterijal = new javax.swing.JLabel();
        txtGrupaMaterijal = new javax.swing.JTextField();
        lblProizvodac = new javax.swing.JLabel();
        txtProizvodac = new javax.swing.JTextField();
        lblOznaka = new javax.swing.JLabel();
        lblKolicinaAmbalaza = new javax.swing.JLabel();
        lblJedinicaMjereAmbalaza = new javax.swing.JLabel();
        lblCijenaAmbalaza = new javax.swing.JLabel();
        lblOpis = new javax.swing.JLabel();
        txtOznaka = new javax.swing.JTextField();
        txtKolicinaAmbalaza = new javax.swing.JTextField();
        txtJedinicaMjereAmbalaza = new javax.swing.JTextField();
        txtCijenaAmbalaza = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        txtUvjet = new javax.swing.JTextField();
        btnTrazi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarOpis = new javax.swing.JTextArea();
        lblPretraga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 420));
        setPreferredSize(new java.awt.Dimension(450, 333));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 200));

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setToolTipText("");
        lista.setDropMode(javax.swing.DropMode.INSERT);
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        lblGrupaMaterijal.setText("Grupa materijala:");

        lblProizvodac.setText("Proizvođač:");

        lblOznaka.setText("Oznaka:");

        lblKolicinaAmbalaza.setText("Pakovanje količina:");

        lblJedinicaMjereAmbalaza.setText("Jedinica mjere:");

        lblCijenaAmbalaza.setText("Cijena pakovanja:");

        lblOpis.setText("Opis:");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        txtUvjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUvjetActionPerformed(evt);
            }
        });

        btnTrazi.setText("Traži");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });

        tarOpis.setColumns(20);
        tarOpis.setRows(5);
        tarOpis.setWrapStyleWord(true);
        jScrollPane2.setViewportView(tarOpis);
        tarOpis.setLineWrap(true);

        lblPretraga.setText("Pretraga po grupi materijala, proizvođaču i oznaci:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtUvjet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTrazi))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrupaMaterijal)
                            .addComponent(lblProizvodac)
                            .addComponent(lblOznaka)
                            .addComponent(lblKolicinaAmbalaza)
                            .addComponent(lblJedinicaMjereAmbalaza)
                            .addComponent(lblCijenaAmbalaza)
                            .addComponent(lblOpis))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCijenaAmbalaza, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtJedinicaMjereAmbalaza, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKolicinaAmbalaza, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOznaka, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProizvodac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGrupaMaterijal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPromjeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisi))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPretraga)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPretraga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrupaMaterijal)
                            .addComponent(txtGrupaMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProizvodac)
                            .addComponent(txtProizvodac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOznaka)
                            .addComponent(txtOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKolicinaAmbalaza)
                            .addComponent(txtKolicinaAmbalaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJedinicaMjereAmbalaza)
                            .addComponent(txtJedinicaMjereAmbalaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCijenaAmbalaza)
                            .addComponent(txtCijenaAmbalaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOpis)
                                .addGap(10, 10, 10))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjeni)
                            .addComponent(btnObrisi)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged

        if (evt.getValueIsAdjusting()) {
            return;
        }

        try {
            this.entitet = lista.getSelectedValue();
            txtGrupaMaterijal.setText(lista.getSelectedValue().getGrupa_materijal());
            txtProizvodac.setText(lista.getSelectedValue().getProizvodac());
            txtOznaka.setText(lista.getSelectedValue().getOznaka());
            txtKolicinaAmbalaza.setText(lista.getSelectedValue().getKolicina_ambalaza().toString());
            txtJedinicaMjereAmbalaza.setText(lista.getSelectedValue().getJedinica_mjere_ambalaza());
            txtCijenaAmbalaza.setText(lista.getSelectedValue().getCijena_ambalaza().toString());
            tarOpis.setText(lista.getSelectedValue().getOpis());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_listaValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        entitet = new Materijal();
        spremi();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        if (lista.getSelectedValue() == null) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
        spremi();
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (lista.getSelectedValue() == null) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
        obrisi();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtUvjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUvjetActionPerformed

    }//GEN-LAST:event_txtUvjetActionPerformed

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
        rezultati = HibernateUtil.getSession().createQuery("from Materijal a where "
                + " a.obrisan=false and concat(a.grupa_materijal, ' ', a.proizvodac, ' ',a.oznaka, ' ') like :uvjet").setString("uvjet", "%" + txtUvjet.getText() + "%").list();
        ucitavanje();
    }//GEN-LAST:event_btnTraziActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCijenaAmbalaza;
    private javax.swing.JLabel lblGrupaMaterijal;
    private javax.swing.JLabel lblJedinicaMjereAmbalaza;
    private javax.swing.JLabel lblKolicinaAmbalaza;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblOznaka;
    private javax.swing.JLabel lblPretraga;
    private javax.swing.JLabel lblProizvodac;
    private javax.swing.JList<Materijal> lista;
    private javax.swing.JTextArea tarOpis;
    private javax.swing.JTextField txtCijenaAmbalaza;
    private javax.swing.JTextField txtGrupaMaterijal;
    private javax.swing.JTextField txtJedinicaMjereAmbalaza;
    private javax.swing.JTextField txtKolicinaAmbalaza;
    private javax.swing.JTextField txtOznaka;
    private javax.swing.JTextField txtProizvodac;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables
}
