/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kovacevic.view;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import kovacevic.controller.Obrada;
import kovacevic.model.Rad;
import kovacevic.pomocno.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Marko Kovačević
 */
public class FormaAnalizaRad extends Forma<Rad> {

    private List<Rad> rezultati;

    /**
     * Creates new form FormaRad
     */
    public FormaAnalizaRad() {
        initComponents();
        setTitle("Analiza Rada");
        obrada = new Obrada();

        ucitaj();
    }

    @Override
    protected void ucitaj() {
        Session session=HibernateUtil.getSession();
        session.clear();
        rezultati = HibernateUtil.getSession().createQuery("from Rad a where a.obrisan=false").list();
        ucitavanje();

    }

    private void ucitavanje() {
        DefaultListModel<Rad> m = new DefaultListModel<>();
        lista.setModel(m);
        rezultati.forEach((s) -> {
            m.addElement(s);

        });

    }

        @Override
    protected void spremi() {
        entitet.setGrupa_radova(txtOpisOperacije.getText());
        entitet.setKategorija_rad(txtBrojOperacije.getText());
        entitet.setCijena(new BigDecimal(txtJedinicniNormativVremena.getText()));
        super.spremi();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        lblOpisOperacije = new javax.swing.JLabel();
        lblBrojOperacije = new javax.swing.JLabel();
        lblJedinicniNormativVremena = new javax.swing.JLabel();
        txtOpisOperacije = new javax.swing.JTextField();
        txtBrojOperacije = new javax.swing.JTextField();
        txtJedinicniNormativVremena = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        lblBrupaRadova = new javax.swing.JLabel();
        lblOznakaNorme = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblGrupaNormi = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        lblBrupaRadova1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        lblCijenaRada = new javax.swing.JLabel();
        txtCijenaVrijeme = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(795, 400));
        setSize(new java.awt.Dimension(0, 0));

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setToolTipText("");
        lista.setDropMode(javax.swing.DropMode.INSERT);
        lista.setMaximumSize(new java.awt.Dimension(1000, 1000));
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        lblOpisOperacije.setText("Opis operacije:");

        lblBrojOperacije.setText("Broj operacije:");

        lblJedinicniNormativVremena.setText("Normativ vremena:");
        lblJedinicniNormativVremena.setToolTipText("");

        txtOpisOperacije.setText("Strojno spravljanje morta");
        txtOpisOperacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpisOperacijeActionPerformed(evt);
            }
        });

        txtBrojOperacije.setText("1");

        txtJedinicniNormativVremena.setText("0.60");
        txtJedinicniNormativVremena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJedinicniNormativVremenaActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblBrupaRadova.setText("Grupa radova:");
        lblBrupaRadova.setToolTipText("");

        lblOznakaNorme.setText("Oznaka norme:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GN 301-203-3.1.", "GN 301-103-5.3." }));

        lblGrupaNormi.setText("Grupa normi:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GN 301 (Zidarski radovi)", "GN 361 (Krovopokrivački radovi)" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Radnik", "Zidar", "Tesar" }));

        lblBrupaRadova1.setText("Kategorija rada:");
        lblBrupaRadova1.setToolTipText("");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "II", "III", "IV", "V", "VI", "VII", "VIII", "I" }));

        lblCijenaRada.setText("Cijena rada:");
        lblCijenaRada.setToolTipText("");

        txtCijenaVrijeme.setText("31.50 (rad * normativ vremena)");
        txtCijenaVrijeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCijenaVrijemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGrupaNormi)
                    .addComponent(lblOznakaNorme)
                    .addComponent(lblBrupaRadova)
                    .addComponent(lblBrupaRadova1)
                    .addComponent(lblOpisOperacije)
                    .addComponent(lblBrojOperacije)
                    .addComponent(lblJedinicniNormativVremena)
                    .addComponent(lblCijenaRada))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCijenaVrijeme)
                    .addComponent(txtJedinicniNormativVremena)
                    .addComponent(txtBrojOperacije)
                    .addComponent(txtOpisOperacije)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPromjeni)
                        .addGap(18, 67, Short.MAX_VALUE)
                        .addComponent(btnObrisi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrupaNormi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOznakaNorme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrupaRadova)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrupaRadova1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrojOperacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrojOperacije))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpisOperacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOpisOperacije))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJedinicniNormativVremena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJedinicniNormativVremena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCijenaVrijeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCijenaRada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnPromjeni)
                    .addComponent(btnObrisi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged

        if (evt.getValueIsAdjusting()) {
            return;
        }

        try {
            this.entitet = lista.getSelectedValue();
            txtOpisOperacije.setText(lista.getSelectedValue().getGrupa_radova());
            txtBrojOperacije.setText(lista.getSelectedValue().getKategorija_rad());
            txtJedinicniNormativVremena.setText(lista.getSelectedValue().getCijena().toString());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_listaValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        entitet = new Rad();
        spremi();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        if (lista.getSelectedValue() == null) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
        spremi();

    }//GEN-LAST:event_btnPromjeniActionPerformed


    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (lista.getSelectedValue() == null) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
        obrisi();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtOpisOperacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpisOperacijeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpisOperacijeActionPerformed

    private void txtJedinicniNormativVremenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJedinicniNormativVremenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJedinicniNormativVremenaActionPerformed

    private void txtCijenaVrijemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCijenaVrijemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCijenaVrijemeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojOperacije;
    private javax.swing.JLabel lblBrupaRadova;
    private javax.swing.JLabel lblBrupaRadova1;
    private javax.swing.JLabel lblCijenaRada;
    private javax.swing.JLabel lblGrupaNormi;
    private javax.swing.JLabel lblJedinicniNormativVremena;
    private javax.swing.JLabel lblOpisOperacije;
    private javax.swing.JLabel lblOznakaNorme;
    private javax.swing.JList<Rad> lista;
    private javax.swing.JTextField txtBrojOperacije;
    private javax.swing.JTextField txtCijenaVrijeme;
    private javax.swing.JTextField txtJedinicniNormativVremena;
    private javax.swing.JTextField txtOpisOperacije;
    // End of variables declaration//GEN-END:variables
}
